name: Merge upstream branches

on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 */12 * * *'
  push: 
    branches: [ main ]
    
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream
        run: |
          git config --global user.name 'd-padmanabhan09'
          git config --global user.email 'dpadmanabhan09@gmail.com'
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v4 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/dpadmanabhan09/source-repo.git
          git fetch upstream

          # Neither forget the -b opt,
          # the sync-fork ref is ambiguous at this stage
          git checkout -b sync-fork origin/main
          git merge --no-edit upstream/main
          git push origin main
          git checkout main
          git merge --no-edit upstream/main
          git push origin main

